# Generated by Django 5.2.12 on 2026-04-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawFredSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("series_id", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=10, max_digits=25, null=True)),
                ("units", models.CharField(max_length=20)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "raw_fred_series",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("series_id", "date"), name="unique_series_date"
                    )
                ],
            },
        ),
    ]
